name: Deploy Streamlit App

on:
  push:
    branches:
      - main  # Thay đổi tên nhánh nếu bạn sử dụng nhánh khác
    paths:
      - '**/*'  # Theo dõi tất cả các thay đổi trong repository, bao gồm dữ liệu và mã nguồn

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Deploy Streamlit app
      run: |
        streamlit run Streamlit_app.py  
